language: node_js

script:
  - xvfb-run DPRO=local ./node_modules/.bin/magellan --local_browsers invisiblechrome --test tests/loginTest.js

node_js:
  - v8
  - v7
  - v6
  - v5

  services:
  - xvfb
# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  hosts:
    - dev.walmart.com
   chrome: stable

before_install:
  # ensure latest npm installed.
  - npm install -g npm
  - npm --version
  - export MAGELLAN_BUILD_NAME=${TRAVIS_JOB_ID}_${TRAVIS_JOB_NUMBER}
  - export MAGELLAN_BUILD_ID=`date +%s`
  - export SAUCE_CONNECT_VERSION=4.4.9
  - export MOCK_HOSTNAME=dev.walmart.com
  - export MAGELLAN_MAX_WORKERS=7
  - google-chrome-stable --headless --disable-gpu --disable-extensions --remote-debugging-port=9222 http://localhost &
